=begin
#ChannelEngine Channel API

#ChannelEngine API for channels

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require "uri"

module ChannelEngineChannelApiClient
  class CancellationApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # Get Cancellations
    # Gets all cancellations created since the supplied date.
    # @param [Hash] opts the optional parameters
    # @option opts [DateTime] :created_since 
    # @return [CollectionOfChannelCancellationResponse]
    def cancellation_index(opts = {})
      data, _status_code, _headers = cancellation_index_with_http_info(opts)
      return data
    end

    # Get Cancellations
    # Gets all cancellations created since the supplied date.
    # @param [Hash] opts the optional parameters
    # @option opts [DateTime] :created_since 
    # @return [Array<(CollectionOfChannelCancellationResponse, Fixnum, Hash)>] CollectionOfChannelCancellationResponse data, response status code and response headers
    def cancellation_index_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: CancellationApi.cancellation_index ..."
      end
      # resource path
      local_var_path = "/v2/cancellations"

      # query parameters
      query_params = {}
      query_params[:'createdSince'] = opts[:'created_since'] if !opts[:'created_since'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['text/plain', 'application/json', 'text/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['apikey']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'CollectionOfChannelCancellationResponse')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: CancellationApi#cancellation_index\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
